In an experiment to investigate the heat of sublimation of iridium, 
the following 27 measurements were made, listed across the rows in the 
order they were taken. The data is contained in the Statistics 1 data set `iridium`. 
 
 
```{r} 
load('stats1.RData') 
iridium 
``` 
 
### (a) 
Use the `R` commands `stem`, `hist`, `boxplot`, and `plot` to make a stem-and-leaf plot, a histogram, a boxplot and a plot of the observations in the order they were taken. Print your plots and comment on the overall pattern and any striking features. 
 
 
### (b) 
Use the `R` commands `median` and `mean` to find the median and the mean.  
Use `mean` in `R` to see how to compute a trimmed mean. 
 
Compute the 10\% and 20\% trimmed means for the iridium data set. 
 
Compare how well the the mean and median and trimmed means represent the centre of this dataset. 
 
 
### (c) 
Use the `R` commands `var` and `sd` to find the sample variance and standard deviation. 
Use the `R` commands `fivenum` and `summary` to find the hinges and the sample quartiles, and use `R` command `IQR` to find the interquartile range (but see comments on 'Hinges and Quartiles' overleaf). 
Again, compare how these values represent the spread of the data. 
 
 
### (d) 
What conclusions do you draw from your plots and numerical summaries? What effect do the outliers have on the numerical and graphical summaries? What would the corresponding results look like if the outliers were removed? 
 
