# load('stats1.RData')
# stem(iridium)
# x11(width = 24, height = 8)
# hist(iridium)
# x11(width = 24, height = 8)
# boxplot(iridium, horizontal = TRUE)
# x11(width = 24, height = 8)
# plot(iridium)

# median(iridium)
# mean(iridium)
# mean(iridium, trim=0.1)

print(var(iridium))
print(sd(iridium))
fivenum(iridium)